# Generated by Django 4.0.4 on 2022-05-24 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Коллекция')),
                ('image', models.ImageField(verbose_name="Картинка")),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='SizeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=4, null=True, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размерный ряд',
                'verbose_name_plural': 'Размерные ряды',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('articul', models.CharField(max_length=255, verbose_name='Артикул')),
                ('images', models.ImageField(upload_to='static/images')),
                ('discount_price', models.IntegerField(verbose_name='Цена со скидкой')),
                ('old_price', models.IntegerField(verbose_name='Цена без скидки')),
                ('description', models.CharField(max_length=500, verbose_name='Описание товара')),
                ('fabric_structure', models.CharField(max_length=100, verbose_name='Состав ткани')),
                ('discount', models.IntegerField(verbose_name='Скидка')),
                ('status', models.CharField(blank=True, choices=[('sales_hit', 'Saleshit'), ('latest', 'Latest')], default=None, max_length=20, null=True, verbose_name='Статус')),
                ('favorite', models.BooleanField(blank=True, verbose_name='Избранное')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.collection', verbose_name='Коллекция')),
                ('colors', models.ManyToManyField(related_name='colors', to='store.color')),
                ('size_line', models.ManyToManyField(related_name='size_lines', to='store.sizeline')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
