# Generated by Django 4.0.4 on 2022-06-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='total_amount_of_productline',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_discount',
            field=models.IntegerField(default=0, verbose_name='Общая скидка'),
        ),
    ]
