# Generated by Django 4.0.4 on 2022-06-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
