# Generated by Django 4.0.4 on 2022-06-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_secondfooter_link_alter_secondfooter_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('call_received_date', models.DateField(auto_now_add=True, verbose_name='Дата обращения')),
                ('callback_type', models.CharField(default='Обратный звонок', max_length=200, verbose_name='Тип обращения')),
                ('called_back', models.BooleanField(default=False, verbose_name='Статус позвонили?')),
            ],
            options={
                'verbose_name': 'Обратный звонок',
                'verbose_name_plural': 'Обратный звонок',
            },
        ),
        migrations.AlterField(
            model_name='secondfooter',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.footer'),
        ),
    ]
