# Generated by Django 4.0.4 on 2022-06-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_total_discount_price_orderitem_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secondfooter',
            options={'verbose_name': 'Футер Вторая вкладка', 'verbose_name_plural': 'Футер Вторая вкладка'},
        ),
        migrations.RemoveField(
            model_name='secondfooter',
            name='link',
        ),
    ]
