# Generated by Django 4.0.4 on 2022-06-06 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_orderitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
