# Generated by Django 4.0.4 on 2022-06-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_shoppingcart_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='discount_price',
            new_name='total_discount_price',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='old_price',
            new_name='total_old_price',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='total_amount_of_productline',
            field=models.IntegerField(null=True, verbose_name='Общее количество товаров'),
        ),
    ]
