# Generated by Django 4.0.4 on 2022-05-25 09:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productcolor_productsizeline_remove_product_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric_structure',
            field=ckeditor.fields.RichTextField(verbose_name='Состав ткани'),
        ),
    ]
