# Generated by Django 4.0.4 on 2022-05-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='favorite',
            field=models.BooleanField(blank=True, null=True, verbose_name='Избранное'),
        ),
    ]
