# Generated by Django 4.0.4 on 2022-05-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_collection_image_alter_product_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='hit',
            field=models.BooleanField(blank=True, null=True, verbose_name='Хит продаж'),
        ),
        migrations.AddField(
            model_name='product',
            name='latest',
            field=models.BooleanField(blank=True, null=True, verbose_name='Новинки'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество в линейке'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_line',
            field=models.CharField(max_length=10, null=True, verbose_name='Размерный ряд'),
        ),
    ]
