# Generated by Django 4.0.4 on 2022-05-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_productcolor_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.CharField(max_length=100, null=True, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric_structure',
            field=models.CharField(max_length=100, null=True, verbose_name='Состав ткани'),
        ),
    ]
