# Generated by Django 4.0.4 on 2022-05-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_about_aboutimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutimages',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AddField(
            model_name='aboutimages',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фотография'),
        ),
    ]
