# Generated by Django 4.0.4 on 2022-05-27 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_aboutimages_options_aboutimages_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutImages',
            new_name='AboutImage',
        ),
    ]
