# Generated by Django 4.0.4 on 2022-05-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_aboutimages_aboutimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='', verbose_name='Иконка')),
                ('headline', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Наше преимущество',
                'verbose_name_plural': 'Наши преимущества',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='aboutimage',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии о нас'},
        ),
        migrations.AlterField(
            model_name='aboutimage',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.about', verbose_name='Страница'),
        ),
    ]
