# Generated by Django 4.0.4 on 2022-05-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slyder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('link', models.SlugField(blank=True, max_length=250, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Слайдер',
            },
        ),
    ]
