# Generated by Django 4.0.4 on 2022-05-27 10:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_publicoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicoffer',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
