# Generated by Django 4.0.4 on 2022-05-27 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.help', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Изображение для Помощь',
                'verbose_name_plural': 'Изображение для Помощь',
            },
        ),
    ]
