# Generated by Django 4.0.4 on 2022-05-30 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_color_productimage_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slyder',
            new_name='Slider',
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name': 'Цвет товара', 'verbose_name_plural': 'Цвета товаров'},
        ),
        migrations.RemoveField(
            model_name='imagehelp',
            name='page',
        ),
    ]
