# Generated by Django 4.0.4 on 2022-06-01 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_bag_alter_product_colors_delete_productcolor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='selected_image',
        ),
    ]
