# Generated by Django 4.0.4 on 2022-06-01 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_remove_bag_selected_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.color', verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
