# Generated by Django 4.0.4 on 2022-06-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_bag_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bag',
            old_name='color',
            new_name='color_id',
        ),
        migrations.AddField(
            model_name='bag',
            name='discount_price',
            field=models.IntegerField(null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='bag',
            name='old_price',
            field=models.IntegerField(null=True, verbose_name='Старая цена'),
        ),
        migrations.AddField(
            model_name='bag',
            name='size_line',
            field=models.CharField(max_length=20, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='bag',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
