# Generated by Django 4.0.4 on 2022-06-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_rename_color_bag_color_id_bag_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouradvantage',
            name='icon',
            field=models.FileField(upload_to='', verbose_name='Иконка'),
        ),
    ]
