# Generated by Django 4.0.4 on 2022-06-01 12:25

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_ouradvantage_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouradvantage',
            name='icon',
            field=models.FileField(upload_to='', validators=[store.validators.validate_file_extension], verbose_name='Иконка'),
        ),
    ]
