# Generated by Django 4.0.4 on 2022-06-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_ouradvantage_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
