# Generated by Django 4.0.4 on 2022-06-02 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_bag_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bag',
            old_name='color_id',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='bag',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='bag',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productimage', verbose_name='Фото'),
        ),
    ]
