# Generated by Django 4.0.4 on 2022-06-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_rename_color_id_bag_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_products', models.IntegerField(verbose_name='Количество линеек')),
                ('number_of_products', models.IntegerField(verbose_name='Количество товаров')),
                ('total_price_without_discount', models.IntegerField(verbose_name='Общая цена без скидки')),
                ('total_price_with_discount', models.IntegerField(verbose_name='Общая цена со скидкой')),
                ('final_total_price', models.IntegerField(verbose_name='Итого цена')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
