# Generated by Django 4.0.4 on 2022-06-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='number_of_products',
            new_name='total_number_of_products',
        ),
    ]
